pastesrht/blueprints/public.py
import json
import pygments
from datetime import timedelta
from flask import Blueprint, current_app, render_template, request, redirect, Response
from flask import url_for, abort
from hashlib import sha1
from markupsafe import Markup
from pastesrht.access import get_paste_or_abort, get_user_or_abort, has_access, DbLock, UserAccess
from pastesrht.types import Paste, PasteFile, PasteVisibility, Blob
from pastesrht.search import apply_search
from pygments import highlight
from pygments.formatters import HtmlFormatter
from pygments.lexers import guess_lexer, guess_lexer_for_filename, TextLexer
from srht.cache import get_cache, set_cache
from srht.database import db
from srht.flask import paginate_query
from srht.graphql import exec_gql, GraphQLOperation, GraphQLUpload
from srht.oauth import current_user, loginrequired
from srht.validation import Validation

public = Blueprint("public", __name__)

@public.route("/")
def index():
    if current_user:
        return render_template("new-paste.html")
    return render_template("index.html")

def create_paste(valid, files, visibility):
    op = GraphQLOperation("""
        mutation CreatePaste($files: [Upload!]!, $visibility: Visibility!) {
            create(files: $files, visibility: $visibility) { id }
        }
    """)
    uploads = []
    for file in files:
        filename = file.get("filename")
        cache_key = "paste.sr.ht:blobs:{0}".format(file.get("sha"))
        contents = get_cache(cache_key)
        if contents is None:
            abort(404)
        uploads.append(GraphQLUpload(filename, contents.decode(), "text/plain"))
    op.var("files", uploads)
    op.var("visibility", visibility.value.upper())
    resp = op.execute("paste.sr.ht", valid=valid)
    if not valid.ok:
        return None
    return resp["create"]["id"]

@public.route("/new-paste", methods=["POST"])
@loginrequired
def new_paste_POST():
    valid = Validation(request)
    contents = valid.require("contents", friendly_name="File contents")
    if contents:
        contents = contents.replace("\r\n", "\n").replace("\r", "\n")
    filename = valid.optional("filename")
    commit = valid.require("commit")
    visibility = valid.require("visibility", cls=PasteVisibility)
    filename = filename.strip() if filename else filename

    files = valid.optional("files")
    files = json.loads(files) if files else []
    valid.kwargs.pop("files", None)

    def dict_without(d, key):
        new_d = d.copy()
        new_d.pop(key)
        return new_d

    if commit == "force":
        valid.errors = [] # Clear validation errors since contents is not required
        paste_id = create_paste(valid, files, visibility)
        if not valid.ok:
            return render_template("new-paste.html", visibility=visibility,
                    **dict_without(valid.kwargs, "visibility"))
        return redirect(url_for(".paste_GET", user=current_user.username,
                sha=paste_id))

    for f in files:
        if f.get("filename") == filename:
            # TODO: Edit this file?
            valid.error("A file with this name already exists in this paste.",
                    field="filename")
    if not valid.ok:
        return render_template("new-paste.html",
                files=files, visibility=visibility,
                **dict_without(valid.kwargs, "visibility"))

    sha = sha1()
    sha.update(contents.encode())
    sha = sha.hexdigest()

    files.append({
        "sha": sha,
        "filename": filename,
        "size": len(contents),
    })
    set_cache("paste.sr.ht:blobs:{0}".format(sha), timedelta(hours=1), contents.encode())

    if commit == "no":
        return render_template("new-paste.html",
                files=files, visibility=visibility)

    paste_id = create_paste(valid, files, visibility)
    if not valid.ok:
        return render_template("new-paste.html",
                files=files, visibility=visibility,
                **dict_without(valid.kwargs, "visibility"))
    return redirect(url_for(".paste_GET", user=current_user.username,
            sha=paste_id))

def _get_shebang(data):
    if not data.startswith('#!'):
        return None
    endline = data.find('\n')
    if endline == -1:
        shebang = data
    else:
        shebang = data[:endline]
    return shebang

def _get_lexer(name, data):
    try:
        return guess_lexer_for_filename(name, data)
    except pygments.util.ClassNotFound:
        try:
            shebang = _get_shebang(data)
            if not shebang:
                return TextLexer()

            return guess_lexer(shebang)
        except pygments.util.ClassNotFound:
            return TextLexer()

def highlight_file(name, content):
    lexer = _get_lexer(name, content)
    formatter = HtmlFormatter()
    style = formatter.get_style_defs('.highlight')
    html = f"<style>{style}</style>" + highlight(content, lexer, formatter)
    return Markup(html)

@public.route("/~<user>")
def pastes_user(user):
    user = get_user_or_abort(user)
    pastes = (Paste.query
            .filter(Paste.user_id == user.id)
            .filter(Paste.sha != None)
            .order_by(Paste.updated.desc()))
    if (current_user and user.id != current_user.id) or not current_user:
        pastes = pastes.filter(Paste.visibility == PasteVisibility.public)

    try:
        terms = request.args.get("search")
        pastes = apply_search(pastes, terms)
        search_error = None
    except ValueError as e:
        search_error = str(e)

    pastes, pagination = paginate_query(pastes)
    return render_template("pastes.html", pastes=pastes, user=user,
            search=terms, search_error=search_error, **pagination)

@public.route("/~<user>/<sha>")
def paste_GET(user, sha):
    user, paste = get_paste_or_abort(user, sha)
    return render_template("paste.html", paste=paste,
            highlight_file=highlight_file)

@public.route("/~<user>/<sha>/manage")
def paste_manage(user, sha):
    user, paste = get_paste_or_abort(user, sha)
    if not has_access(current_user, paste, UserAccess.write):
        abort(401)

    return render_template("paste-manage.html", paste=paste)

@public.route("/~<user>/<sha>/manage", methods=['POST'])
def paste_manage_POST(user, sha):
    user, paste = get_paste_or_abort(user, sha)
    if not has_access(current_user, paste, UserAccess.write):
        abort(401)

    valid = Validation(request)
    visibility = valid.optional("visibility",
            cls=PasteVisibility,
            default=paste.visibility)

    exec_gql(current_app.site, """
        mutation UpdatePaste($id: String!, $visibility: Visibility!) {
            update(id: $id, visibility: $visibility) { id }
        }
    """, id=sha, visibility=visibility.value.upper())

    return redirect(url_for('.paste_manage', user=user.username, sha=sha))

@public.route("/~<user>/<sha>/delete")
def paste_delete(user, sha):
    user, paste = get_paste_or_abort(user, sha)
    if not has_access(current_user, paste, UserAccess.write):
        abort(401)

    return render_template("paste-delete.html", paste=paste)

@public.route("/~<user>/<sha>/delete", methods=['POST'])
def paste_delete_POST(user, sha):
    user, paste = get_paste_or_abort(user, sha)
    if not has_access(current_user, paste, UserAccess.write):
        abort(401)

    exec_gql(current_app.site, """
        mutation DeletePaste($id: String!) {
            delete(id: $id) { id }
        }
    """, id=sha)
    return redirect(url_for('.index'))

@public.route("/blob/<sha>")
def blob_GET(sha):
    blob = Blob.query.filter(Blob.sha == sha).one_or_none()
    if not blob:
        abort(404)
    return Response(blob.contents, mimetype="text/plain")

@public.route("/pastes")
@loginrequired
def pastes():
    return redirect(url_for('.pastes_user', user=current_user.username))

pastesrht/templates/index.html
{% extends "layout.html" %}
{% block content %}
<div class="row">
  <div class="col-md-8">
    <p>
      Welcome to <strong>{{domain}}</strong>! This service provides ad-hoc
      hosting for your text files. Features of this service include:
    </p>
    <ul>
      <li>Syntax highlighting</li>
      <li>Revision history</li>
      <li>Rendered Markdown files</li>
    </ul>
    <a
      class="btn btn-primary"
      href="{{get_origin("meta.sr.ht", external=True)}}/register"
    >Register here {{icon('caret-right')}}</a>
    or
    <a href="{{oauth_url}}">
      Log in {{icon('caret-right')}}
    </a>
    to get started.
  </div>
</div>
{% endblock %}

pastesrht/templates/new-paste.html
{% extends "layout.html" %}
{% block content %}
<div class="row">
  <div class="col-lg-4">
    <p>
      Welcome back, {{ current_user.username }}! This is the
      {{cfg("sr.ht", "site-name")}} paste hosting service. Documentation
      for its use is
      <a href="https://man.sr.ht/paste.sr.ht">available here</a>.
    </p>
    <a href="{{ url_for(".pastes") }}" class="btn btn-block btn-default view-pastes">
      View your pastes {{icon('caret-right')}}
    </a>
  </div>
  <div class="col-lg-8">
    <form action="/new-paste" method="POST">
      {{csrf_token()}}
      {% if files %}
      <input type="hidden" name="files" value="{{ json(files) }}" />
      {% endif %}
      <div class="form-group">
        <input
          type="text"
          id="filename"
          name="filename"
          class="form-control {{valid.cls('filename')}}"
          value="{{ filename if filename else  '' }}"
          placeholder="File name (optional)" />
        {{valid.summary("filename")}}
      </div>
      <div class="form-group">
        <textarea
          name="contents"
          id="contents"
          class="form-control {{valid.cls('contents')}}"
          placeholder="Contents"
          rows="15"
        >{{contents if contents else ''}}</textarea>
        {{valid.summary("contents")}}
      </div>
      {{valid.summary()}}
      <div class="pull-right">
        <fieldset class="form-group float-left">
          <div class="form-check form-check-inline">
            <label
              class="form-check-label"
              title="Publically visible and listed on your profile"
            >
              <input
                class="form-check-input"
                type="radio"
                name="visibility"
                value="public"
                {{ "checked" if visibility and visibility.value == "public" else "" }}
              > Public
            </label>
          </div>
          <div class="form-check form-check-inline">
            <label
              class="form-check-label"
              title="Visible to anyone with the link, but not shown on your profile"
            >
              <input
                class="form-check-input"
                type="radio"
                name="visibility"
                value="unlisted"
                {{ "checked" if not visibility or visibility.value == "unlisted" else "" }}
              > Unlisted
            </label>
          </div>
          <div class="form-check form-check-inline">
            <label
              class="form-check-label"
              title="Only visible to you"
            >
              <input
                class="form-check-input"
                type="radio"
                name="visibility"
                value="private"
                {{ "checked" if visibility and visibility.value == "private" else "" }}
              > Private
            </label>
          </div>
        </fieldset>
        <button
          type="submit"
          name="commit"
          value="no"
          class="btn btn-default"
          style="margin-right: 1rem"
        >Add another file {{icon('caret-right')}}</button>
        <button
          type="submit"
          name="commit"
          value="yes"
          class="btn btn-primary"
        >Create paste {{icon('caret-right')}}</button>
      </div>
      <div class="clearfix"></div>
      {% if files %}
      <div class="event-list" style="margin-top: 1rem">
        <div class="file-list event">
          {% for file in files %}
          <div style="grid-column-start: 1">{{file.filename}}</div>
          <div class="text-muted" style="margin-left: 1rem">
            <span title="{{"{0:0o}".format(33188)}}">
              {{stat.filemode(33188)}}
            </span>
          </div>
          <div class="text-muted" style="margin-left: 1rem">
            <span title="{{ file.size }} bytes">
              {{humanize.naturalsize(file.size,
                binary=True).replace("Byte", "byte")}}
            </span>
          </div>
          {% endfor %}
        </div>
      </div>
      <button
        type="submit"
        name="commit"
        value="force"
        class="btn btn-default"
      >Use only these files {{icon('caret-right')}}</button>
      {% endif %}
    </form>
  </div>
</div>
<script src="/static/paste.sr.ht/ace.js"></script>
<script src="/static/paste.sr.ht/ext-modelist.js"></script>
<script>
  var contents = document.getElementById("contents");
  var form = document.querySelector("form");
  var input = document.createElement("input");
  input.type = "hidden";
  input.value = contents.value;
  input.name = "contents";
  form.appendChild(input);
  var editor = ace.edit(contents, {
    behavioursEnabled: false,
  });
  editor.on("change", e => {
    input.value = editor.getValue();
  });
  document.querySelector(".ace-tm").className += " " + contents.className;
  const modelist = ace.require("ace/ext/modelist");
  const getModeByFileExtension = path => {
    const mode = modelist.getModeForPath(path);
    return mode ? mode.mode : null;
  }
  const filename = document.getElementById("filename");
  const setMode = () =>
    editor.getSession().setMode(getModeByFileExtension(filename.value));
  filename.addEventListener("keyup", setMode);
  setMode();
</script>
<style>
  .ace-tm {
    height: 400px;
    font-size: 0.9rem;
    border-radius: 0;
  }
</style>
{% endblock %}

pastesrht/templates/paste-base.html
{% macro link(endpoint, title) %}
<a
  class="nav-link {% if request.endpoint.split('.')[-1] == endpoint[1:] %}active{% endif %}"
  href="{{ url_for(endpoint, user=paste.user.username, sha=paste.sha) }}"
>{{ title }}</a>
{% endmacro %}
{% extends "layout-full.html" %}
{% block body %}
<div class="header-tabbed">
  <div class="container-fluid">
    <ul class="nav nav-tabs">
      <h2>
        <a href="{{ url_for("public.pastes_user",
          user=paste.user.username) }}"
        >{{ paste.user.canonical_name -}}</a>/<wbr>
        {%- if len(paste.files) == 1 -%}
        {{paste.files[0].filename or paste.sha[:7]}}
        {%- else -%}
        {{paste.sha[:7]}}
        {%- endif %}
        {% if paste.visibility.value != 'public' %}
        <small class="text-muted">
          {{ paste.visibility.value }}
        </small>
        {% endif %}
      </h2>
      <li class="nav-item">
        {%- if len(paste.files) == 1 -%}
        {{ link(".paste_GET", "view paste") }}
        {%- else -%}
        {{ link(".paste_GET", "view paste (" + str(len(paste.files)) + " files)") }}
        {%- endif -%}
      </li>
      {%- if current_user.id == paste.user_id -%}
      <li class="nav-item">
        {{ link(".paste_manage", "manage") }}
      </li>
      <li class="nav-item">
        {{ link(".paste_delete", "delete") }}
      </li>
      {%- endif %}
    </ul>
  </div>
</div>
{% block paste_body %}
{% endblock %}
{% endblock %}

pastesrht/templates/paste-delete.html
{% extends "paste-base.html" %}
{% macro paste_name(paste) %}
  {%- if len(paste.files) == 1 -%}
  {{paste.files[0].filename or paste.sha[:7]}}
  {%- else -%}
  {{paste.sha[:7]}}
  {%- endif -%}
{% endmacro %}
{% block paste_body %}
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <p>
        This will permanently delete your paste,
	<strong>{{ paste.user.canonical_name -}}/{{ paste_name(paste) }}</strong>.
        This cannot be undone.
      </p>
      <form method="POST">
        {{csrf_token()}}
        <button type="submit" class="btn btn-danger">
          Delete {{ paste_name(paste) }} {{icon("caret-right")}}
        </button>
        <a
          href="{{ url_for('.paste_GET', user=paste.user.username, sha=paste.sha) }}"
          class="btn btn-default"
        >Nevermind</a>
      </form>
    </div>
  </div>
</div>
{% endblock %}

pastesrht/templates/paste-manage.html
{% extends "paste-base.html" %}
{% block paste_body %}
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h4>Visibility</h4>
      <form method="POST">
        {{csrf_token()}}
        <fieldset class="form-group">
          <div class="form-check form-check-inline">
            <label
              class="form-check-label"
              title="Publically visible and listed on your profile"
            >
              <input
                class="form-check-input"
                type="radio"
                name="visibility"
                value="public"
                {{ "checked" if paste.visibility.value == "public" else "" }}
              > Public
            </label>
          </div>
              <div class="form-check form-check-inline">
                <label
                  class="form-check-label"
                  title="Visible to anyone with the link, but not shown on your profile"
                >
                  <input
                    class="form-check-input"
                    type="radio"
                    name="visibility"
                    value="unlisted"
                    {{ "checked" if paste.visibility.value == "unlisted" else "" }}
                  > Unlisted
                </label>
              </div>
                  <div class="form-check form-check-inline">
                    <label
                      class="form-check-label"
                      title="Only visible to you"
                    >
                      <input
                        class="form-check-input"
                        type="radio"
                        name="visibility"
                        value="private"
                        {{ "checked" if paste.visibility.value == "private" else "" }}
                      > Private
                    </label>
                  </div>
        </fieldset>
        <button type="submit" class="btn btn-primary pull-right">
          Save {{icon("caret-right")}}
        </button>
      </form>
    </div>
  </div>
</div>
{% endblock %}

pastesrht/templates/paste.html
{% extends "paste-base.html" %}
{% block title %}
<title>
{% if len(paste.files) == 1 %}
{{paste.files[0].filename or paste.sha[:7]}} &mdash; paste.sr.ht
{% else -%}
{{paste.sha[:7]}} &mdash; paste.sr.ht
{%- endif %}
</title>
{% endblock %}
{% block paste_body %}
{% for file in paste.files %}
<div class="header-extension" style="margin-bottom: 0;" id="{{file.filename}}">
  <div class="container-fluid">
    <span style="display: inline-block; width: 1rem">
      <a class="filename" href="#{{file.filename}}">#</a>
    </span>
    <span>{{file.filename or ""}}</span>
    <span class="text-muted" style="margin-left: 1rem">
      <span title="{{"{0:0o}".format(33188)}}">
        {{stat.filemode(33188)}}
      </span>
    </span>
    <span class="text-muted" style="margin-left: 1rem">
      <span title="{{ len(file.blob.contents) }} bytes">
        {{humanize.naturalsize(len(file.blob.contents),
          binary=True).replace("Byte", "byte")}}
      </span>
    </span>
    <span class="text-muted" style="margin-left: 1rem">
      <a href="{{ url_for(".blob_GET", sha=file.blob.sha) }}">
        View raw
      </a>
    </span>
  </div>
</div>
{% if file.filename and file.filename.endswith(".md") %}
<div class="container markdown-content">
  {{ file.blob.contents|render_markdown }}
</div>
{% else %}
<div class="container-fluid other-content">
  <div class="code-view">
    <pre class="ruler"><span>{% for i in range(80) %} {% endfor %}</span></pre>
    <pre class="lines">{% for line in file.blob.contents.split("\n") %}<a
      href="#{{file.filename}}-L{{loop.index}}"
      id="{{file.filename}}-L{{loop.index}}"
      >{{loop.index}}</a>{% if not loop.last %}
{% endif %}{% endfor %}</pre>
    {{highlight_file(file.filename or "", file.blob.contents)}}
  </div>
</div>
{% endif %}
{% endfor %}
{% endblock %}

pastesrht/templates/pastes.html
{% extends "layout.html" %}
{% block content %}
<div class="row">
  <div class="col-md-4" style="margin-bottom: 1rem">
    {% if user == current_user %}
    <p>
      Welcome back, {{ current_user.username }}! This is the
      {{cfg("sr.ht", "site-name")}} paste hosting service. Documentation
      for its use is
      <a href="https://man.sr.ht/paste.sr.ht">available here</a>.
    </p>
    <a href="/" class="btn btn-block btn-default">
      New paste {{icon('caret-right')}}
    </a>
   {% else %}
    <h2>
      ~{{ user.username }}
    </h2>
    {% if user.location %}
    <p>{{user.location}}</p>
    {% endif %}
    {% if user.url %}
    <p>
      <a
        href="{{user.url}}"
        target="_blank"
        rel="me noopener noreferrer nofollow"
      >{{user.url}}</a>
    </p>
    {% endif %}
    {% if user.bio %}
    {{user.bio | md}}
    {% endif %}
    {% endif %}
  </div>
  <div class="col-md-8 event-list">
    <form style="margin-bottom: 0.5rem">
      <label for="search" class="sr-only">Search pastes</label>
      <input
        name="search"
        type="text"
        placeholder="Search pastes...     filename     visibility:unlisted     sha:d54e32b"
        class="form-control{% if search_error %} is-invalid{% endif %}"
        value="{{ search if search else "" }}" />
      {% if search_error %}
        <div class="invalid-feedback">{{ search_error }}</div>
      {% endif %}
    </form>

    {% for paste in pastes %}
    <div class="event">
      <h3>
        <a href="{{ url_for(".paste_GET",
          user=paste.user.username, sha=paste.sha) }}"
        >
          {% if len(paste.files) == 1 %}
          {{paste.files[0].filename or paste.sha[:7]}}
          {% else -%}
          {{paste.sha[:7]}}
          {%- endif %}
        </a>
        <div class="pull-right">
          {% if paste.visibility.value != 'public' %}
          <small>
            {{ paste.visibility.value }}
          </small>
          {% endif %}
          <small>{{paste.created | date}}</small>
        </div>
      </h3>
      <div class="file-list">
        {% for file in paste.files %}
        <div style="grid-column-start: 1">{{file.filename or ""}}</div>
        <div class="text-muted">
          <span title="{{"{0:0o}".format(33188)}}">
            {{stat.filemode(33188)}}
          </span>
        </div>
        <div class="text-muted">
          <span title="{{ len(file.blob.contents) }} bytes">
            {{humanize.naturalsize(len(file.blob.contents),
              binary=True).replace("Byte", "byte")}}
          </span>
        </div>
        {% endfor %}
      </div>
    </div>
    {% endfor %}
    {{pagination()}}
  </div>
</div>
{% endblock %}